name: gamestop
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: newfla <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  path: ^1.4.1
  html: ^0.13.4

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
